exports.get_pieces = function() { return article_pieces };

var article_pieces = {
  piece_1: {
     type: "drop",
     dropHeaderText: "Book I",
     collapseTag: "piece-collapse-1",
     content: {
       content_1: "He was a man who looked at what ought to be done, not to the reputation which is got by a man's acts.",
    },
    add_styles: "",
  },
  piece_2: {
     type: "drop",
     dropHeaderText: "Book II",
     collapseTag: "piece-collapse-2",
     content: {
       content_1: "When you wake up in the morning, tell yourself: The people I deal with today will be meddling, ungrateful, arrogant, dishonest, jealous, and surly. They are like this because they can't tell good from evil.",
       content_2: "Whatever this is that I am, it is flesh and a little spirit and an intelligence.",
       content_3: "All that is from the gods is full of Providence.",
       content_4: "There is a limit to the time assigned you, and if you don't use it to free yourself it will be gone and never return.",
       content_5: "You will find rest from vain fancies if you perform every act in life as though it were your last.",
       content_6: "Thou seest how few be the things, the which if a man has at his command his life flows gently on and is divine.",
       content_7: "Give thyself time to learn something new and good, and cease to be whirled around.",
       content_8: "This thou must always bear in mind, what is the nature of the whole...",
       content_9: "Yet living and dying, honour and dishonour, pain and pleasure, riches and poverty, and so forth are equally the lot of good men and bad. Things like these neither elevate nor degrade; and therefore they are no more good than they are evil.",
       content_10: "The longest-lived and the shortest-lived man, when they come to die, lose one and the same thing.",
       content_11: "Remember that all is opinion.",
       content_12: "No state sorrier than that of the man who keeps up a continual round, and pries into 'the secrets of the nether world,' as saith the poet, and is curious in conjecture of what is in his neighbour's heart.",
       content_13: "Though thou be destined to live three thousand years and as many myriads besides, yet remember that no man loseth other life than that which he liveth, nor liveth other than that which he loseth",
       content_14: "As for life, it is a battle and a sojourning in a strange land; but the fame that comes after is oblivion.",
    },
    add_styles: ""
  },
  piece_3: {
     type: "drop",
     dropHeaderText: "Book III",
     collapseTag: "piece-collapse-3",
     content: {
       content_1: "What means all this?",
       content_2: "Waste not the remnant of thy life in those imaginations touching other folk, whereby thou contributest not to the common weal.",
       content_3: "The lot assigned to every man is suited to him, and suits him to itself.",
    },
    add_styles: ""
  },
  piece_4: {
     type: "drop",
     dropHeaderText: "Book IV",
     collapseTag: "piece-collapse-4",
     content: {
       content_1: "The ruling power within, when it is in its natural state, is so related to outer circumstances that it easily changes to accord with what can be done and what is given it to do.",
       content_2: "Let no act be done at haphazard, nor otherwise than according to the finished rules that govern its kind.",
       content_3: "By a tranquil mind I mean nothing else than a mind well ordered.",
       content_4: "Men seek retreats for themselves, houses in the country, sea-shores, and mountains; and thou too art wont to desire such things very much. But this is altogether a mark of the most common sort of men, for it is in thy power whenever thou shalt choose to retire into thyself. For nowhere either with more quiet or more freedom from trouble does a man retire than into his own soul.",
       content_5: "The universe is change; our life is what our thoughts make it.",
       content_6: "Think on this doctrine,—that reasoning beings were created for one another's sake; that to be patient is a branch of justice, and that men sin without intending it.",
       content_7: "Nothing can come out of nothing, any more than a thing can go back to nothing.",
       content_8: "If mind is common to us, then also the reason, whereby we are reasoning beings, is common.' If this be so, then also the reason which enjoins what is to be done or left undone is common. If this be so, law also is common; if this be so, we are citizens; if this be so, we are partakers in one constitution; if this be so, the Universe is a kind of Commonwealth.",
       content_9: "Death, like generation, is a secret of Nature.",
       content_10: "That which makes the man no worse than he was makes his life no worse: it has no power to harm, without or within.",
       content_11: "Whatever happens at all happens as it should; you will find this true, if you watch narrowly.",
       content_12: "Death hangs over thee. While thou livest, while it is in thy power, be good.",
       content_13: "Many the lumps of frankincense on the same altar; one falls there early and another late, but it makes no difference.",
       content_14: "How much time he gains who does not look to see what his neighbor says or does or thinks, but only at what he does himself, to make it just and holy.",
       content_15: "Doth perfect beauty stand in need of praise at all? Nay; no more than law, no more than truth, no more than loving kindness, nor than modesty.",
       content_16: "Whatever is in any way beautiful hath its source of beauty in itself, and is complete in itself; praise forms no part of it. So it is none the worse nor the better for being praised.",
       content_17: "All that is harmony for you, my Universe, is in harmony with me as well. Nothing that comes at the right time for you is too early or too late for me. Everything is fruit to me that your seasons bring, Nature. All things come of you, have their being in you, and return to you.",
       content_18: "'Let your occupations be few,' says the sage, 'if you would lead a tranquil life.'",
       content_19: "Love the little trade which thou hast learned, and be content therewith.",
       content_20: "Remember this— that there is a proper dignity and proportion to be observed in the performance of every act of life.",
       content_21: "All is ephemeral — fame and the famous as well.",
       content_22: "Observe always that everything is the result of a change, and get used to thinking that there is nothing Nature loves so well as to change existing forms and to make new ones like them.",
       content_23: "Search men's governing principles, and consider the wise, what they shun and what they cleave to.",
       content_24: "Constantly regard the universe as one living being, having one substance and one soul; and observe how all things have reference to one perception, the perception of this one living being; and how all things act with one movement; and how all things are the cooperating causes of all things which exist; observe too the continuous spinning of the thread and the contexture of the web.",
       content_25: "Thou art a little soul bearing about a corpse, as Epictetus used to say.",
       content_26: "Time is a sort of river of passing events, and strong is its current; no sooner is a thing brought to sight than it is swept by and another takes its place, and this too will be swept away.",
       content_27: "All that happens is as usual and familiar as the rose in spring and the crop in summer.",
       content_20: "That which comes after ever conforms to that which has gone before.",
       content_29: "Mark how fleeting and paltry is the estate of man - yesterday in embryo, tomorrow a mummy or ashes. So for the hairsbreadth of time assigned to thee, live rationally, and part with life cheerfully, as drops the ripe olive, extolling the season that bore it and the tree that matured it.",
       content_30: "Deem not life a thing of consequence. For look at the yawning void of the future, and at that other limitless space, the past.",
       content_31: "Always take the short cut; and that is the rational one. Therefore say and do everything according to soundest reason.",
    },
    add_styles: ""
  },
  piece_5: {
     type: "drop",
     dropHeaderText: "Book V",
     collapseTag: "piece-collapse-5",
     content: {
       content_1: "At dawn, when you have trouble getting out of bed, tell yourself: ‘I have to go to work – as a human being. What do I have to complain of, if I’m going to do what I was born for – the things I was brought into the world to do? Or is this what I was created for? To huddle under the blankets and stay warm?’",
       content_2: "You don't love yourself enough. Or you'd love your nature too, and what it demands of you. People who love what they do wear themselves down doing it, they even forget to wash or eat. Do you have less respect for your own nature than the engraver does for engraving, the dancer for the dance, the miser for money or the social climber for status? When they're really possessed by what they do, they'd rather stop eating and sleeping than give up practicing their arts. Is helping others less valuable to you? Not worth your effort?",
       content_3: "How easy it is to repel and to wipe away every impression which is troublesome or unsuitable, and immediately to be in all tranquility.",
       content_4: "Some people, when they do someone a favor, are always looking for a chance to call it in. And some aren't, but they're still aware of it--still regard it as a debt. But others don't even do that. They're like a vine that produces grapes without looking for anything in return.",
       content_5: "A horse at the end of the race...A dog when the hunt is over...A bee with its honey stored...And a human being after helping others. They don't make a fuss about it. They just go on to something else, as the vine looks forward to bearing fruit again in season. We should be like that. Acting almost unconsciously.",
       content_6: "The other reason is that what happens to the individual is a cause of well-being in what directs the world--of its well-being, its fulfillment, or its very existence, even. Because the whole is damaged if you cut away anything--anything at all--from its continuity and its coherence. Not only its parts, but its purposes. And that's what you're doing when you complain: hacking and destroying.",
       content_7: "Not to feel exasperated, or defeated, or despondent because your days aren't packed with wise and moral actions. But to get back up when you fail, to celebrate behaving like a human--however imperfectly--and fully embrace the pursuit that you've embarked on.",
       content_8: "The things you think about determine the quality of your mind. Your soul takes on the color of your thoughts.",
       content_9: "It is crazy to want what is impossible. And impossible for the wicked not to do so.",
       content_10: "Nothing happens to anyone that he can't endure.",
       content_11: "Things have no hold on the soul. They have no access to it, cannot move or direct it. It is moved and directed by itself alone. It takes the things before it and interprets them as it sees fit.",
       content_12: "In a sense, people are our proper occupation. Our job is to do them good and put up with them. But when they obstruct our proper tasks, they become irrelevant to us--like sun, wind, and animals. Our actions may be impeded by them, but there can be no impeding our intentions or our dispositions. Because we can accommodate and adapt. The mind adapts and converts to its own purposes the obstacle to our acting. The impediment to action advances action. What stands in the way becomes the way.",
       content_13: "Prize that which is best in the universe; and this is that which useth everything and ordereth everything.",
       content_14: "The mind is the ruler of the soul. It should remain unstirred by agitations of the flesh--gentle and violent ones alike. Not mingling with them, but fencing itself off and keeping those feelings in their place. When they make their way into our thoughts, through the sympathetic link between mind and body, don't try to resist the sensation. The sensation is natural. But don't let the mind start in with judgments, calling it 'good' or 'bad.'",
       content_15: "Live with the gods.",
       content_16: "Art thou angry with him whose arm-pits stink? Art thou angry with him whose mouth smells foul? What good will this anger do thee?",
       content_17: "The intelligence of the universe is social.",
    },
    add_styles: ""
  },
  piece_6: {
     type: "drop",
     dropHeaderText: "Book VI",
     collapseTag: "piece-collapse-6",
     content: {
       content_1: "Ἔσω βλέπε· μηδενὸς πράγματος μήτε ἡ ἰδία ποιότης μήτε ἡ ἀξία παρατρεχέτω σε.",
       content_2: "The controlling Intelligence understands its own nature, and what it does, and whereon it works.",
       content_3: "The best revenge is not to be like your enemy.",
       content_4: "Do not think that what is hard for you to master is humanly impossible; but if a thing is humanly possible, consider it to be within your reach.",
       content_5: "If any man can convince me and bring home to me that I do not think or act aright, gladly will I change; for I search after truth, by which man never yet was harmed. But he is harmed who abideth on still in his deception and ignorance.",
       content_6: "Death,—a stopping of impressions through the senses, and of the pulling of the cords of motion, and of the ways of thought, and of service to the flesh.",
       content_7: "Take heed not to be transformed into a Caesar, not to be dipped in the purple dye, for it does happen. Keep yourself therefore, simple, good, pure, grave, unaffected, the friend of justice, religious, kind, affectionate, strong for your proper work. Wrestle to be the man philosophy wished to make you. Reverence the gods, save men. Life is brief; there is but one harvest of earthly existence, a holy disposition and neighborly acts.",
       content_8: "Revere the gods and help men. Short is life.",
       content_9: "I consist of a little body and a soul.",
       content_10: "Adapt yourself to the environment in which your lot has been cast, and show true love to the fellow-mortals with whom destiny has surrounded you.",
       content_11: "But if we judge only those things which are in our power to be good or bad, there remains no reason either for finding fault with God or standing in a hostile attitude to man.",
       content_12: "What is not good for the swarm is not good for the bee.",
       content_13: "How many together with whom I came into the world are already gone out of it.",
    },
    add_styles: ""
  },
  piece_7: {
     type: "drop",
     dropHeaderText: "Book VII",
     collapseTag: "piece-collapse-7",
     content: {
       content_1: "Understand however that every man is worth just so much as the things are worth about which he busies himself.",
       content_2: "How many, once lauded in song, are given over to the forgotten; and how many who sung their praises are clean gone long ago!",
       content_3: "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.",
       content_4: "All things are implicated with one another, and the bond is holy; and there is hardly anything unconnected with any other things. For things have been co-ordinated, and they combine to make up the same universe. For there is one universe made up of all things, and one god who pervades all things, and one substance, and one law, and one reason.",
       content_5: "To a rational being it is the same thing to act according to nature and according to reason.",
       content_6: "Be thou erect, or be made erect.",
       content_7: "Is any man afraid of change? Why what can take place without change?",
       content_8: "Soon you will have forgotten the world, and soon the world will have forgotten you.",
       content_9: "It is man's peculiar duty to love even those who wrong him.",
       content_10: "Nature which governs the whole will soon change all things which thou seest, and out of there substance will make other things, and again other things from the substance of them, in order that the world may ever be new.",
       content_11: "Think not so much of what thou hast not as of what thou hast: but of the things which thou hast, select the best, and then reflect how eagerly they would have been sought, if thou hadst them not. At the same time, however, take care that thou dost not, through being so pleased with them, accustom thyself to overvalue them, so as to be disturbed if ever thou shouldst not have them.",
       content_12: "Retire into thyself. The rational principle which rules has this nature, that it is content with itself when it does what is just, and so secures tranquility.",
       content_13: "Wipe out the imagination. Stop pulling the strings. Confine thyself to the present. ...Divide and distribute every object into the causal [formal] and the material. ...Let the wrong which is done by a man stay there where the wrong was done.",
       content_14: "Direct thy attention to what is said. Let thy understanding enter into the things that are doing and the things which do them.",
       content_15: "Adorn thyself with simplicity and with indifference towards the things which lie between virtue and vice. Love mankind. Follow God. The poet says that Law rules all. And it is enough to remember that law rules all.",
       content_16: "About fame... Just as the sand-dunes, heaped one upon another, hide each the first, so in life the former deeds are quickly hidden by those that follow after.",
       content_17: "From Plato: the man who has an elevated mind and takes a view of all time and of all substance, dost thou suppose it possible for him to think that human life is anything great? It is not possible, he said. Such a man then will think that death also is no evil.",
       content_18: "From Antisthenes: It is royal to do good and be abused.",
       content_19: "It is a base thing for the countenance to be obedient and to regulate and compose itself as the mind commands, and for the mind not to be regulated and composed by itself.",
       content_20: "It is not right to vex ourselves at things, For they care not about it.",
       content_21: "If the gods care not for me and for my children, There is a reason for it.",
       content_22: "For thus it is, men of Athens, in truth: wherever a man has placed himself thinking it is the best place for him, or has been placed by a commander, there in my opinion he ought to stay and to abide the hazard, taking nothing into the reckoning, either death or anything else, before the baseness [of deserting his post].",
       content_23: "Look round at the courses of the stars, as if thou wert going along with them; and constantly consider the changes of the elements into one another; for such thoughts purge away the filth of the terrene life.",
       content_24: "This is a fine saying of Plato: That he who is discoursing about men should look also at earthly things as if he viewed them from some higher place; should look at them... a mixture of all things and an orderly combination of contraries.",
       content_25: "Thou mayest foresee... the things which will be. For they will certainly be of like form, and it is not possible that they should deviate from the order of things now: accordingly to have contemplated human life for forty years is the same as to have contemplated it for ten thousand years.",
       content_26: "That which had grown from the earth, to the earth, But that which has sprung from heavenly seed, Back to the heavenly realms returns. This is either a dissolution of the mutual involution of the atoms, or a similar dispersion of the unsentient elements.",
       content_27: "Another may be more expert in casting [throwing] his opponent; but he is not more social, nor more modest, nor better disciplined to meet all that happens, nor more considerate with respect to the faults of his neighbors.",
       content_28: "Where any work can be done conformably to the reason which is common to gods and men, there we have nothing to fear; for where we are able to get profit by means of the activity which is successful and proceeds according to our constitution, there no harm is to be suspected.",
       content_29: "Everywhere and at all times it is in thy power piously to acquiesce in thy present condition, and to behave justly to those who are about thee, and to exert thy skill upon thy present thoughts, that nothing shall steal into them without being well examined.",
       content_30: "Every being ought to do that which is according to its constitution; and all other things have been constituted for the sake of the superior, but the rational for the sake of one another.",
       content_31: "Consider thyself to be dead, and to have completed thy life up to the present time; and live according to nature the remainder which is allowed thee.",
       content_32: "Love that only which happens to thee and is spun with the thread of thy destiny. For what is more suitable?",
       content_33: "Why then dost thou choose to act in the same way? and why dost thou not leave these agitations which are foreign to nature, to those who cause them and those who are moved by them? And why art thou not altogether intent upon the right way of making use of things which happen to thee? for then thou wilt use them well, and they will be material for thee. Only attend to thyself, and resolve to be a good man in every act which thou doest; and remember...",
       content_34: "Look within. Within is the fountain of the good, and it will ever bubble up, if thou wilt ever dig.",
       content_35: "The art of life is more like the wrestler's art than the dancer's, in respect of this, that it should stand ready and firm to meet onsets which are sudden and unexpected.",
       content_36: "Every soul, the philosopher says, is involuntarily deprived of truth; consequently in the same way it is deprived of justice and temperance and benevolence and everything of the kind. It is most necessary to keep this in mind, for thus thou wilt be more gentle towards all.",
       content_37: "In the case of most pains let this remark of Epicurus aid thee, that the pain is neither intolerable nor everlasting, if thou bear in mind that it has its limits, and if thou addest nothing to it in imagination...",
       content_38: "Very little is needed to make a happy life.",
       content_39: "To live each day as though one's last, never flustered, never apathetic, never attitudinizing – here is perfection of character.",
       content_40: "The nature of the All moved to make the universe.",
    },
    add_styles: ""
  },
  piece_8: {
     type: "drop",
     dropHeaderText: "Book VIII",
     collapseTag: "piece-collapse-8",
     content: {
       content_1: "On the occasion of every act ask thyself, How is this with respect to me? Shall I repent of it? A little time and I am dead, and all is gone.",
       content_2: "You may break your heart, but men will still go on as before.",
       content_3: "Constantly and, if it be possible, on the occasion of every impression on the soul, apply to it the principles of Physic, of Ethic, and of Dialectic.",
       content_4: "To change your mind and to follow him who sets you right is to be nonetheless the free agent that you were before.",
       content_5: "Nature has had regard in everything no less to the end than to the beginning and the continuance, just like a man who throws up a ball. What good is it then for the ball to be thrown up, or harm for it to come down... what good is it to the bubble while it holds together, or what harm when it is burst?",
       content_6: "Short-lived are both the praiser and the praised, and rememberer and the remembered: and all this in a nook of this part of the world; and not even here do all agree, no, not any one with himself: and the whole earth too is a point.",
       content_7: "Look to the essence of a thing, whether it be a point of doctrine, of practice, or of interpretation.",
       content_8: "Thou sufferest justly: for thou choosest rather to become good to-morrow than to be good to-day.",
       content_9: "Remember this, then, that this little compound, thyself, must either be dissolved, or they poor breath must be extinguished, or be removed and placed elsewhere.",
       content_10: "It is satisfaction to a man to do the proper works of a man.",
       content_11: "There are three relations [between thee and other things]: the one to the body which surrounds thee; the second to the divine cause from which all things come to all; and the third to those who live with thee.",
       content_12: "Suppose that thou hast detached thyself from the natural unity... yet here there is this beautiful provision, that it is in thy power again to unite thyself. God has allowed this to no other part, after it has been separated and cut asunder, to come together again. ...he has distinguished man, for he has put it in his power not to be separated at all from the universal ...he has allowed him to be returned and to be united and to resume his place as a part.",
       content_13: "As the nature of the universal has given to every rational being all the powers that it has, so we have received from it this power also. For as the universal nature converts and fixes in its predestined place everything which stands in the way and opposes it, and makes such things a part of itself, so also the rational animal is able to make every hindrance its own material, and to use it for such purpose as it may have designed.",
       content_14: "Remember that neither the future nor the past pains thee, but only the present. But this is reduced to a very little, if thou only circumscribest it, and chidest thy mind, if it is unable to hold out against even this.",
       content_15: "If thou canst see sharp, look and judge wisely, says the philosopher.",
       content_16: "In the constitution of that rational animal I see no virtue which is opposed to justice, but I see a virtue which is opposed to love of pleasure, and that is temperance.",
       content_17: "The things... which are proper to the understanding no other man is used to impede, for neither fire, nor iron, nor tyrant, nor abuse, touches it in any way. When it has been made a sphere, it continues a sphere.",
       content_18: "It is not fit that I should give myself pain, for I have never intentionally given pain even to another.",
       content_19: "If...it be a thing external that causes thy grief, know, that it is not that properly that doth cause it, but thine own conceit and opinion concerning the thing: which thou mayest rid thyself of, when thou wilt.",
       content_20: "The mind which is free from passions is a citadel, for man has nothing more secure to which he can fly for refuge and for the future be inexpugnable. He then who has not seen this is an ignorant man: but he who has seen it and does not fly to this refuge is unhappy.",
       content_21: "The universal nature has no external space; but the wondrous part of her art is that though she has circumscribed herself, everything which is within her which appears to decay and to grow old and to be useless she changes into herself, and again makes other new things from these very same, so that she requires neither substance from without nor wants a place into which she may cast that which decays. She is content then with her own space, and her own matter, and her own art.",
       content_22: "No carelessness in your actions. No confusion in your words. No imprecision in your thoughts.",
       content_23: "A man standing by a spring of clear, sweet water and cursing it. While the fresh water keeps on bubbling up. He can shovel mud into it, or dung, and the stream will carry it away, wash itself clean, remain unstained.",
       content_24: "He who does not know what the world is, does not know where he is. And he who does not know for what purpose the world exists, does not know who he is, nor what the world is. But he who has failed in any one of these things could not even say for what purpose he exists himself. What then dost thou think of him who [avoids or] seeks the praise of those who applaud, of men who know not either where they are or who they are?",
       content_25: "You want praise from people who kick themselves every fifteen minutes, the approval of people who despise themselves. (Is it a sign of self-respect to regret nearly everything you do?)",
       content_26: "No longer let thy breathing only act in concert with the air which surrounds thee, but let thy intelligence also now be in harmony with the intelligence which embraces all things. For the intelligent power is no less diffused in all parts and pervades all things for him who is willing to draw it to him than the aërial power for him who is able to respire it.",
       content_27: "He who fears death either fears to lose all sensation or fears new sensations. In reality, you will either feel nothing at all, and therefore nothing evil, or else, if you can feel any sensations, you will be a new creature, and so will not have ceased to have life.",
       content_28: "Men exist for the sake of one another. Teach them then or bear with them.",
       content_29: "An arrow has one motion and the mind another. Even when pausing, even when weighing conclusions, the mind is moving forward, toward its goal.",
    },
    add_styles: ""
  },
  piece_9: {
     type: "drop",
     dropHeaderText: "Book IX",
     collapseTag: "piece-collapse-9",
     content: {
       content_1: "The nature of the universe is the nature of things that are. Now, things that are have kinship with things that are from the beginning. Further, this nature is styled Truth; and it is the first cause of all that is true.",
       content_2: "He would be the finer gentleman that should leave the world without having tasted of lying or pretence of any sort, or of wantonness or conceit.",
       content_3: "Think not disdainfully of death, but look on it with favor; for even death is one of the things that Nature wills.",
       content_4: "A wrongdoer is often a man who has left something undone, not always one who has done something.",
       content_5: "Blot out vain pomp; check impulse; quench appetite; keep reason under its own control.",
       content_6: "Things that have a common quality ever quickly seek their kind.",
       content_7: "All things are the same,—familiar in enterprise, momentary in endurance, coarse in substance. All things now are as they were in the day of those whom we have buried.",
       content_8: "The happiness and unhappiness of the rational, social animal depends not on what he feels but on what he does; just as his virtue and vice consist not in feeling but in doing.",
       content_9: "All things are changing; and thou thyself art in continuous mutation and in a manner in continuous destruction and the whole universe to.",
       content_10: "Turn thy thoughts now to the consideration of thy life, thy life as a child, as a youth, thy manhood, thy old age, for in these also every change was a death. Is this anything to fear?",
       content_11: "Hasten [to examine] thy own ruling faculty and that of the universe and that of thy neighbor: thy own, that thy may make it just; and that of the universe, that thou mayst remember of what thou art a part; and that of thy neighbor, that thy mayst know whether he has acted ignorantly or with knowledge, and that thou mayst also consider that his ruling faculty is akin to thine.",
       content_12: "As thou thyself art a component part of a social system, so let every act of thine be a component part of social life. Whatever act of thine that has no reference, either immediately or remotely, to a social end, this tears asunder thy life, and does not allow it to be one, and it is of the nature of a mutiny, just as when in a popular assembly a man acting by himself stands apart from the general agreement.",
       content_13: "The universal intelligence puts itself in motion for every separate effect... or it puts itself in motion once, and everything else comes by way of a sequence in a manner; or individual elements are the origin of all things. In a word, if there is a god, all is well; and if chance rules, do not thou be governed by it.",
       content_14: "If man reflects on the changes and transformations which follow one another like wave after wave and their rapidity, he will despise everything which is perishable.",
       content_15: "Do what nature now requires. Set thyself in motion, if it is in thy power, and do not look about thee to see if any one will observe it; nor yet expect Plato's Republic: but be content if the smallest thing goes on well, and consider such an event to be no small matter.",
       content_16: "Let there be freedom from perturbations with respect to the things which come from the external cause; and let there be justice in the things done by virtue of the internal cause, that is, let there be movement and action terminating in this, in social acts, for this is according to thy nature.",
       content_17: "He that dies in extreme old age will be reduced to the same state with him that is cut down untimely.",
       content_18: "The rottenness of the matter which is the foundation of everything!",
       content_19: "Either all things proceed from one intelligent source and come together as in one body, and the part ought not to find fault with what is done for the benefit of the whole; or there are only atoms, and nothing else than a mixture and dispersion. Why, then, art thou disturbed? Say to this ruling faculty, Art thou dead, art thou corrupted, art thou playing the hypocrite, art thou become a beast, dost thou herd and feed with the rest?",
       content_20: "Why dost thou not pray... to give thee the faculty of not fearing any of the things which thou fearest, or of not desiring any of the things which thou desirest, or not being pained at anything, rather than pray that any of these things should not happen or happen?",
       content_21: "Is it not better to use what is in thy power like a free man than to desire in a slavish and abject way what is not in thy power?",
       content_22: "One man prays thus: How shall I be able to lie with that woman? Do thou pray thus: How shall I not desire to lie with her? Another prays: How shall I be released from this? Another prays: How shall I not desire to be released? Another thus: How shall I not lose my little son? Thou thus: How shall I not be afraid to lose him? In fine, turn thy prayers this way, and see what comes.",
       content_23: "Art thy not content that thou hast done something conformable to thy nature, and dost thou seek to be paid for it? Just as if the eye demanded recompense for seeing, or the feet for walking. For as these members are formed for a particular purpose... so also is man formed by nature to acts of benevolence.",
    },
    add_styles: ""
  },
  piece_10: {
     type: "drop",
     dropHeaderText: "Book X",
     collapseTag: "piece-collapse-10",
     content: {
       content_1: "Wilt thou then, my soul, never be good and simple and one and naked, more manifest than the body which surrounds thee? Wilt thou never enjoy an affectionate and contented disposition? Wilt thou never be full and without a want of any kind, longing for nothing more, nor desiring anything, either animate of inanimate, for the enjoyment of pleasures? nor yet desiring time wherein thou shalt have longer enjoyment, or place, or pleasant climate, or society of men with whom thou mayst live in harmony? but wilt thou be satisfied with thy present condition, and pleased with all that is around thee, and wilt thou convince thyself that thou hast everything and that it comes from the gods, that everything is well for thee, and will be well whatever shall please them, and whatever they shall give for the conservation of the perfect living being, the good and just and beautiful, which generates and holds together all things, and contains and embraces all things which are dissolved for the production of other like things? Wilt thou never be such that thou shalt so dwell in community with gods and men as neither to find fault with them at all, nor to be condemned by them?",
       content_2: "Use these rules then, and trouble thyself about nothing else.",
       content_3: "If a man is mistaken, instruct him kindly and show him his error. But if thou art not able, blame thyself, or blame not even thyself.",
       content_4: "Whatever may happen to thee, it was prepared for thee from all eternity; and the implication of causes was from eternity spinning the thread of thy being, and of that which is incident to it.",
       content_5: "The whole contains nothing which is not or its advantage; and all natures indeed have this common principle, but the nature of the universe has this principle besides, that it cannot be compelled even by any external cause to generate anything harmful to itself.",
       content_6: "By remembering then that I am a part of such a whole, I shall be content with everything that happens. And inasmuch as I am in a manner intimately related to the parts which are of the same kind with myself, I shall do nothing unsocial, but I shall rather direct myself to the things which are of the same kind with myself, and I shall turn all my efforts to the common interest, and divert them from the contrary.",
       content_7: "Remember that the term Rational was intended to signify a discriminating attention to every several thing and freedom from negligence; and that Equanimity is the voluntary acceptance of things which are assigned to thee by the common nature; and the Magnanimity is the elevation of the intelligent part above the pleasurable or painful sensations of the flesh, and above that poor thing called fame, and death, and all such things. If then, thou maintainest thyself in the possession of these names, without desiring to be called by these names by others, thou wilt be another person and wilt enter into another life.",
       content_8: "Rememberest the gods, and that they wish not to be flattered, but wish all reasonable beings to be made like themselves; and... rememberest that what does the work of a fig-tree is a fig-tree, and that what does the work of a dog is a dog, and that what does the work of a bee is a bee, and that what does the work of a man is a man.",
       content_9: "Acquire the contemplative way of seeing how all things change into one another, and constantly attend to it, and exercise thyself about this part [of philosophy]. For nothing is so much adapted to produce magnanimity. ...But as to what any man shall say or think about him, or do against him, he never even thinks of it, being himself contented with these two things: with acting justly in what he now does, and being satisfied with what is now assigned to him; and he lays aside all distracting and busy pursuits, and desires nothing else than to accomplish the straight course through the law, and by accomplishing the straight course to follow God.",
       content_10: "What need is there of suspicious fear, since it is in thy power to inquire what ought to be done? And if thy seest clear, go by this way content, without turning back: but if thy dost not see clear, stop and take the best advisers. But if any other things oppose thee, go on according to thy powers with due consideration, keeping to that which appears to be just. For it is best to reach this object, and if thou dost fail, let thy failure be in attempting this. He who follows reason in all things is both tranquil and active at the same time, and also cheerful and collected.",
       content_11: "To her who gives and takes back all, to nature, the man who is instructed and modest says, Give what thou wilt; take back what thou wilt. And he says this not proudly, but obediently and well pleased with her.",
       content_12: "Live as on a mountain. ...Let men see, let them know a real man who lives according to nature. If they cannot endure him, let them kill him. For that is better than to live thus.",
       content_13: "Waste no more time arguing what a good man should be. Be one.",
       content_14: "Constantly contemplate the whole of time and the whole of substance, and consider that all individual things as to substance are a grain of a fig, and as to time the turning of a gimlet.",
       content_15: "Look at everything that exists, and observe that it is already in dissolution and change, and as it were putrefaction or dispersion, or that everything is so constituted in nature as to die.",
       content_16: "'The earth loveth the shower,' and 'the holy æther knoweth what love is.' The Universe, too, loves to create whatsoever is destined to be made.",
       content_17: "Let this always be plain to thee, that this piece of land is like any other; and that all things here are the same with all things on the top of a mountain, or on the sea-shore, or wherever thou chooses to be. For thou wilt find just what Plato says, Dwelling within the walls of the city as in a shepherd's fold on a mountain.",
       content_18: "What is my ruling faculty now to me? and of what nature am I now making it? and for what purpose am I now using it? is it void of understanding? is it loosed and rent asunder from social life? is it melted and mixed with the poor flesh so as to move together with it?",
       content_19: "He who flies from his master is a runaway; but the law is master, and he who breaks the law is a runaway. And he also who is grieved or angry or afraid, is dissatisfied because something has been or is or shall be of the things which are appointed by Him who rules all things, and He is Law, and assigns to every man what is fit. He then who fears or is grieved or is angry is a runaway.",
       content_20: "All those [events in history] were such dramas as we see now, only with different actors.",
       content_21: "Only to the rational animal is it given to follow voluntarily what happens; but simply to follow is a necessity imposed on all.",
       content_22: "When thou art offended at any man's fault, forthwith turn to thyself and reflect in what manner thou doest error thyself... For by attending to this thou wilt quickly forget thy anger, if this consideration is also added, that the man is compelled; for what else could he do? or, if thou art able, take away from him the compulsion.",
       content_23: "Continuously thou wilt look at human things as smoke and nothing at all; especially if thou reflectest at the same time, that what has once changed will never exist again in the infinite duration of time. But thou, in what a brief space of time is thy existence? And why art thou not content to pass through this short time in an orderly way?",
       content_24: "What matter and opportunity [for thy activity] art thou avoiding? For what else are all these things, except exercises for the reason, when it has viewed carefully and by examination into their nature the things which happen in life? Persevere then until thou shalt have made these things thy own, as the stomach which is strengthened makes all things its own, as the blazing fire makes flame and brightness out of everything that is thrown into it.",
       content_25: "Let it not be in any man's power to say truly of thee that thou art not simple or that thou art not good; but let him be a liar whoever shall think anything of this kind about thee; and this is altogether in thy power.",
       content_26: "It is not given to a cylinder to move everywhere by its own motion, nor yet to water nor to fire nor to anything else which is governed by nature or an irrational soul, for the things which check them and stand in the way are many. But intelligence and reason are able to go through everything that opposes them, and in such manner as they are formed by nature and as they choose. Place before thy eyes this facility with which the reason will be carried through all things, as fire upwards, as a stone downwards, as a cylinder down an inclined surface, and seek for nothing further. For all other obstacles either affect the body only, which is a dead thing; or, except for opinion and the yielding of reason itself, they do not crush nor do any harm of any kind; for if they did, he who felt it would immediately become bad.",
       content_27: "In the case of all things which have a certain constitution, whatever harm may happen to any of them, that which is affected becomes consequently worse; but in like case, a man becomes both better... and more worthy of praise, by making the right use of these accidents.",
       content_28: "And finally remember that nothing harms him who is really a citizen, which does not harm the state; nor yet does anything harm the state which does not harm law [order]; and of these things which are called misfortunes not one harms law. What then does not harm law does not harm either state or citizen.",
       content_29: "'Leaves, some the wind scatters on the ground — So is the race of man.' Leaves, also, are thy children; and leaves, too, are they who cry out so if they are worthy of credit, or bestow their praise, or on the contrary curse, or secretly blame and sneer; and leaves, in like manner, are those who shall receive and transmit a man's fame to after-times. For all such things as these 'are produced in the season of spring,' as the poet says; then the wind casts them down; then the forest produces other leaves in their places. But a brief existence is common to all things, and yet thou avoidest and pursuest all things as if they would be eternal.",
       content_30: "A little time, and thou shalt close thy eyes; and him who has attended thee to thy grave, another soon will lament.",
       content_31: "The healthy eye ought to see all visible things and not to say, I wish for green things; for this is the condition of the diseased eye. And the healthy hearing and smelling ought to be ready to perceive all that can be heard and smelled. And the healthy stomach ought to be with respect to all food just as the mill with respect to all things which it is formed to grind. And accordingly the healthy understanding ought to be prepared for everything which happens; but that which says, Let my dear children live, and let all men praise whatever I may do, is an eye which seeks for green things, or teeth which seek for soft things.",
       content_32: "There is no man so fortunate that there shall not be by him when he is dying some who are pleased with what is going to happen. Suppose that he was a good and a wise man, will there not be at least some one to say to himself, Let us at last breathe freely, being relieved from this schoolmaster? It is true that he was harsh to none of us, but I perceive that he tacitly condemns us.—This is what is said of a good man. But in our own case how many other things are there for which there are many who wish to get rid of us.",
       content_33: "Remember that what pulls the strings is the force hidden within; there lies the power to persuade, there the life,—there, if one must speak out, the real man.",
       content_34: "In contemplating thyself never include the vessel which surrounds thee, and these instruments which are attached about it. For they are like an ax, differing only in this, that they grow to the body. For indeed there is no more use in these parts without the cause which moves and checks them than in the weaver's shuttle, and the writer's pen, and the driver's whip.",
    },
    add_styles: ""
  },
  piece_11: {
     type: "drop",
     dropHeaderText: "Book XI",
     collapseTag: "piece-collapse-11",
     content: {
       content_1: "Have I done something for the general interest? Well then I have had my reward. Let this always be present to thy mind, and never stop doing such good.",
       content_2: "There is no nature which is inferior to art, the arts imitate the nature of things.",
       content_3: "The man who is honest and good ought to be exactly like a man who smells strong, so that the bystander as soon as he comes near him must smell whether he choose or not.",
       content_4: "Socrates used to call the opinions of the many by the name of Lamiae, bugbears to frighten children.",
       content_5: "And virtue they will curse, speaking harsh words.",
    },
    add_styles: ""
  },
  piece_12: {
     type: "drop",
     dropHeaderText: "Book XII",
     collapseTag: "piece-collapse-12",
     content: {
       content_1: "All those things at which thou wishest to arrive by a circuitous road, thou canst have now, if thou dost not refuse them to thyself.",
       content_2: "If it is not right, do not do it, if it is not true, do not say it. For let thy efforts be —",
       content_3: "Consider that everything is opinion, and opinion is in thy power.",
       content_4: "Know the joy of life by piling good deed on good deed until no rift or cranny appears between them.",
       content_5: "Everything harmonizes with me, which is harmonious to thee, O Universe. Nothing for me is too early or too late, which is in due time for thee. There is one light of the sun, though it is interrupted by walls, mountains and infinite other things. There is one common substance, though it is distributed among countless bodies which have their several qualities. There is one soul, though it is distributed among several natures and individual limitations. There is one intelligent soul, though it seems to be divided.",
       content_6: "Depart then satisfied, for he also who releases thee is satisfied.",
    },
    add_styles: ""
  },
  piece_13: {
     type: "drop",
     dropHeaderText: "Dmitri's Stoicisms",
     collapseTag: "piece-collapse-13",
     content: {
       content_1: "Work hard and take heed: If thou finish not thy day's work by the setting of the sun, thou shall do well to not resume thy labor at the rising of the next sun. A task which cannot be completed within the day is not worth two.",
       content_2: "If a man cuts his hand from his wrist and offers to you the severed appendage, do not take it! scorn him his stupidity.",
       content_3: "Ten dogs do not replace one lost lamb, for dogs and lambs are different creatures. One barks, while the other bleats. There are more differences too. In the future, we shall breed lamb-dogs and serve them with two pastes: one mashed from tomatoes and the other from mustard seeds.",
       content_4: "Often do you find yourself in wonder at the stupidity of those around you? Why are you alone rational in this foolish world of Women & Men? Contemplate not more poor idiot, for we shall all die and death suffers no wisdom.",
       content_5: "Wednesdays are for ice cream, Thursdays are for sorbet, Fridays are for Creme Brulee. Feast mortal, none of these treats shall follow you into the abyss. The Afterlife shall greet you with only bags of Sour Patch Kids candy, the cat food of demons.",
       content_6: "If you count one-thousand stars, then you must count one more so as to reach one-thousand & one; be wary yet! for if you count ten-thousand, you must count one less, so as to stoop to nine-thousand & nine-hundred & ninety-nine. I know not why.",
       content_7: "Those who live without clear sight live with (at the very least) blurry vision. Those who live without blurry vision, either see clearly or see nothing at all and I see no distinction between these two. Me, myself ... I often squint, my eyes are poor and so I require spectacles.",
    },
    add_styles: ""
  }
};